export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const LOGOUT_USER_REQUESTED = "LOGOUT_USER_REQUESTED";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const ADD_TAG_REQUESTED = "ADD_TAG_REQUESTED";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_FAIL = "ADD_TAG_FAIL";

export const REMOVE_TAG_REQUESTED = "REMOVE_TAG_REQUESTED";
export const REMOVE_TAG_SUCCESS = "REMOVE_TAG_SUCCESS";
export const REMOVE_TAG_FAIL = "REMOVE_TAG_FAIL";

export const EDIT_TAG_REQUESTED = "EDIT_TAG_REQUESTED";
export const EDIT_TAG_SUCCESS = "EDIT_TAG_SUCCESS";
export const EDIT_TAG_FAIL = "EDIT_TAG_FAIL";
