export const ADD_URL_REQUESTED = "ADD_URL_REQUESTED";
export const ADD_URL_SUCCESS = "ADD_URL_SUCCESS";
export const ADD_URL_FAIL = "ADD_URL_FAIL";

export const REMOVE_URL_REQUESTED = "REMOVE_URL_REQUESTED";
export const REMOVE_URL_SUCCESS = "REMOVE_URL_SUCCESS";
export const REMOVE_URL_FAIL = "REMOVE_URL_FAIL";

export const EDIT_URL_REQUESTED = "EDIT_URL_REQUESTED";
export const EDIT_URL_SUCCESS = "EDIT_URL_SUCCESS";
export const EDIT_URL_FAIL = "EDIT_URL_FAIL";

export const FETCH_URL_TITLES_REQUESTED = "FETCH_URL_TITLES_REQUESTED";
export const FETCH_URL_TITLES_RESET = "FETCH_URL_TITLES_RESET";
export const FETCH_URL_TITLES_SUCCESS = "FETCH_URL_TITLES_SUCCESS";
export const FETCH_URL_TITLES_FAIL = "FETCH_URL_TITLES_FAIL";
